### ISSUE TITLE
Is it possible to show multiple line strings? 

### ISSUE THREAD

**Issue by Ambrsoe** [ShawnLin013/NumberPicker#56]
I set the string to numberpicker ,but when the string item is too long.It can't show string completely.
(e.g. "Bonaire, Sint Eustatius and Saba" ,in numberpicker only show "naire, Sint Eustatius and Sa")

========
我遇到一個問題是當我放入string到numberpicker裡，都可以正常顯示但是在字數較長的項目中，他就會致中顯示並且切掉頭尾的字。

https://images.plurk.com/5iWgsLHdBR38UVF9kD7k.jpg

**Comment by ShawnLin013** [comment]
Hi,
Show multiple lines is possible, but I think the text in NumberPicker should not be too long.

**Comment by esrabindra** [comment]
How is it possible to show multiples line? Can you please give some idea?

**Comment by AmbroseChen** [comment]
@esrabindra Unfortunately,I didn't show multiple lines then.It's hard to remember the reason not insistent making it multiple lines.I just made the textsize smaller.

**Comment by esrabindra** [comment]
@AmbroseChen I resize the text size but get same problem because the text that i used in numberpicker is too large. The client requirement is to show multiline view for large text. The text used in number picker is dynamic and depend on the server(backend). Any idea to show whole text in numberpicker.
@ShawnLin013  Please give some idea or add multiline feature if possible.

**Comment by alizarei95** [comment]
@ShawnLin013 how to show multiline text in number picker?
